In [1]:
import torch
print(torch.__version__)

2.5.1+cpu


# Create Matrix

In [ ]:
import random

matrix1 =[[random.random() for _ in range(3)] for _ in range(3)]
matrix2 =[[random.random() for _ in range(3)] for _ in range(3)]
print(matrix)

[[0.6684261064738296, 0.008935681436927578, 0.289239148089244], [0.9014767529381309, 0.8140773341238821, 0.6033345128840484], [0.21628006350542917, 0.8901350330615148, 0.41321266533089873]]


In [33]:
# result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]


# Tensor 

easy way to represent matrices and have easy access to mathematical functions

In [32]:
tensor1 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
tensor2 = torch.tensor([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])
result = tensor1 * tensor2
print(tensor1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


TENSOR MANIPULATION

In [31]:
print(tensor1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [30]:
# tensor1([[1.,2.,3.],
#          [4.,5.,6.],
#          [7.,8.,9.]])

In [28]:
# reshape = tensor1.view(1,9)
reshape = tensor1.view(9,1)
print(reshape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [12]:
sliced_tensor = tensor1[:,1]
print(sliced_tensor)

tensor([2., 5., 8.])


In [8]:
boolean_tensor = tensor1[tensor1 > 5]
print(boolean_tensor)

tensor([6., 7., 8., 9.])


In [10]:
concatenate_tensor = torch.cat((tensor1,tensor2),dim=0)
print(concatenate_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [ ]:
stacked_tensors = torch.stack((tensor1,tensor2),dim=1)
print(stacked_tensors)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[9., 8., 7.],
         [6., 5., 4.],
         [3., 2., 1.]]])


## Tensor Methods

In [22]:
# displays that it is a 3x3 [3,3]
# <tensor1.shape
tensor1.size()


torch.Size([3, 3])

In [23]:
#2 deimensional
tensor1.ndim

2

In [17]:
tensor1.dtype

torch.float32

In [27]:
unsqueezed_tensor = tensor1.unsqueeze(0)
unsqueezed_tensor.ndim
unsqueezed_tensor

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [25]:
raveled_tensor = tensor1.ravel()
raveled_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
reshaped_tensor = tensor1.reshape(1,9)
reshaped_tensor

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [37]:
# split_tensor = tensor1.split(1,dim=0)
t1,t2,t3 = tensor1.split(1,dim=0)
split_tensor

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]), tensor([[7., 8., 9.]]))

In [38]:
sum_tensor = tensor1.sum()
mean_tensor = tensor1.mean()
mean_tensor

tensor(5.)

In [39]:
max_val, max_idx = tensor1.max(dim=0)
print(max_idx, max_val)

tensor([2, 2, 2]) tensor([7., 8., 9.])
